colorScheme = "fire"
homepage.layout = "profile"
homepage.showRecent = true
mainPosts = ["posts"]
defaultAppearance = 'light'
autoSwitchApperance = true
enableSearch = true
footer.showScrollToTop = true
footer.showAppearanceSwitcher = true
footer.showThemeAttribution = false
footer.showCopyright = true

[fathomAnalytics]
site = "FGWGRBBV"