colorScheme = "ocean"
homepage.layout = "profile"
homepage.showRecent = false
homepage.mainSections = ["posts"]
showAppearanceSwitcher = true
enableSearch = true
showScrollToTop = true

[fathomAnalytics]
site = "RCFFTRLS"
domain = "jamesmillner.dev"
