colorScheme = "ocean"
homepage.layout = "profile"
homepage.showRecent = true
mainPosts = ["posts"]
defaultAppearance = 'light'
autoSwitchApperance = true
enableSearch = true
footer.showScrollToTop = true
footer.showAppearanceSwitcher = true

[fathomAnalytics]
site = "FGWGRBBV"