colorScheme = "ocean"
homepage.layout = "profile"
homepage.showRecent = true
homepage.mainSections = ["posts"]
showAppearanceSwitcher = true
enableSearch = true
showScrollToTop = true

[fathomAnalytics]
site = "RCFFTRLS"